name: Create Release

on:
  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: AssetStoreRelease

      - name: Merge master into AssetStoreRelease
        run: |
          git config --local user.name ${{ secrets.COMMITTER_NAME }}
          git config --local user.email ${{ secrets.COMMITTER_EMAIL }}
          git fetch origin master --depth 1
          git rebase origin/master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Run CreateRelease.cs
        run: |
          cd .github  # Change the working directory
          dotnet script CreateRelease.cs

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Assets/Mirror/version.txt
          git commit -m "release!: Asset Store Release" -a
          git push origin AssetStoreRelease
